/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deaornotdeal;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author akbal
 */
public class game extends javax.swing.JFrame {

    /**
     * Creates new form game
     */
    public game() {
        initComponents();
    }
    private Integer seleccionados=7;
    private Integer Turno=0;
    private Integer intentos=6;
    private Double total = 3418391.01;
    private Double banca;
    private Double price;
    
    Object[] options ={
    "acepto","No Acepto"
    };
    Double[] porcentaje ={.005,.01,.07,.1,.15,.2,.25,.35,.5};
            
    private void make_this(){
        lblmsm.setText("Seleccione los maletines a eliminar");
        seleccionados--;
        lblcout.setText(seleccionados.toString());
        banca=total*porcentaje[Turno];
        Double imp=banca;
if (seleccionados==0){
int oferta = JOptionPane.showOptionDialog(this,String.format("$ %.2f",imp),"Oferta de la banca",JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,null,options,options[1]);
if(oferta == JOptionPane.NO_OPTION){
Turno++;
if(Turno<=5){
seleccionados = 6-Turno;
intentos=6-Turno;
lblcout.setText(intentos.toString());
}
if(Turno>5&&Turno<=8){
seleccionados=1;
intentos=1;
lblcout.setText("1");}
if(Turno==9){
    Double win = price;
JOptionPane.showMessageDialog(this,String.format("Ganaste $ %.2f",win), "Fin del juego",JOptionPane.INFORMATION_MESSAGE);
System.exit(0);
}
}
if(oferta == JOptionPane.YES_OPTION){
JOptionPane.showMessageDialog(this,String.format("Ganaste $ %.2f",imp), "Fin del juego",JOptionPane.INFORMATION_MESSAGE);
System.exit(0);
}
}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        pnl5 = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        pnl10 = new javax.swing.JPanel();
        lbl4 = new javax.swing.JLabel();
        pnl50 = new javax.swing.JPanel();
        lbl5 = new javax.swing.JLabel();
        pnl75 = new javax.swing.JPanel();
        lbl6 = new javax.swing.JLabel();
        pnl100 = new javax.swing.JPanel();
        lbl7 = new javax.swing.JLabel();
        pnl200 = new javax.swing.JPanel();
        lbl8 = new javax.swing.JLabel();
        pnl300 = new javax.swing.JPanel();
        lbl9 = new javax.swing.JLabel();
        pnl400 = new javax.swing.JPanel();
        lbl10 = new javax.swing.JLabel();
        pnl500 = new javax.swing.JPanel();
        lbl11 = new javax.swing.JLabel();
        pnl750 = new javax.swing.JPanel();
        lbl12 = new javax.swing.JLabel();
        pnl25 = new javax.swing.JPanel();
        lbl13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnl1k = new javax.swing.JPanel();
        lbl14 = new javax.swing.JLabel();
        pnl5k = new javax.swing.JPanel();
        lbl15 = new javax.swing.JLabel();
        pnl10k = new javax.swing.JPanel();
        lbl16 = new javax.swing.JLabel();
        pnl25k = new javax.swing.JPanel();
        lbl17 = new javax.swing.JLabel();
        pnl50k = new javax.swing.JPanel();
        lbl18 = new javax.swing.JLabel();
        pnl75k = new javax.swing.JPanel();
        lbl19 = new javax.swing.JLabel();
        pnl100k = new javax.swing.JPanel();
        lbl20 = new javax.swing.JLabel();
        pnl200k = new javax.swing.JPanel();
        lbl21 = new javax.swing.JLabel();
        pnl300k = new javax.swing.JPanel();
        lbl22 = new javax.swing.JLabel();
        pnl400k = new javax.swing.JPanel();
        lbl23 = new javax.swing.JLabel();
        pnl500k = new javax.swing.JPanel();
        lbl24 = new javax.swing.JLabel();
        pnl750k = new javax.swing.JPanel();
        lbl25 = new javax.swing.JLabel();
        pnl1m = new javax.swing.JPanel();
        lbl26 = new javax.swing.JLabel();
        case1 = new javax.swing.JToggleButton();
        case2 = new javax.swing.JToggleButton();
        case3 = new javax.swing.JToggleButton();
        case4 = new javax.swing.JToggleButton();
        case5 = new javax.swing.JToggleButton();
        case6 = new javax.swing.JToggleButton();
        case11 = new javax.swing.JToggleButton();
        case14 = new javax.swing.JToggleButton();
        case19 = new javax.swing.JToggleButton();
        case24 = new javax.swing.JToggleButton();
        case12 = new javax.swing.JToggleButton();
        case15 = new javax.swing.JToggleButton();
        case20 = new javax.swing.JToggleButton();
        case7 = new javax.swing.JToggleButton();
        case25 = new javax.swing.JToggleButton();
        case8 = new javax.swing.JToggleButton();
        case13 = new javax.swing.JToggleButton();
        case16 = new javax.swing.JToggleButton();
        case21 = new javax.swing.JToggleButton();
        case26 = new javax.swing.JToggleButton();
        case9 = new javax.swing.JToggleButton();
        case10 = new javax.swing.JToggleButton();
        case17 = new javax.swing.JToggleButton();
        case18 = new javax.swing.JToggleButton();
        case22 = new javax.swing.JToggleButton();
        case23 = new javax.swing.JToggleButton();
        jPanel30 = new javax.swing.JPanel();
        lblmsm = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblcout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblselec = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 3, true));

        pnl1.setBackground(new java.awt.Color(255, 255, 0));
        pnl1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl1.setText("0.01");

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl1)
                .addContainerGap())
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl1)
        );

        pnl2.setBackground(new java.awt.Color(255, 255, 0));
        pnl2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl2.setText("1");

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl2)
                .addContainerGap())
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl2))
        );

        pnl5.setBackground(new java.awt.Color(255, 255, 0));
        pnl5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl3.setText("5");

        javax.swing.GroupLayout pnl5Layout = new javax.swing.GroupLayout(pnl5);
        pnl5.setLayout(pnl5Layout);
        pnl5Layout.setHorizontalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl3)
                .addContainerGap())
        );
        pnl5Layout.setVerticalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl3))
        );

        pnl10.setBackground(new java.awt.Color(255, 255, 0));
        pnl10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl4.setText("10");

        javax.swing.GroupLayout pnl10Layout = new javax.swing.GroupLayout(pnl10);
        pnl10.setLayout(pnl10Layout);
        pnl10Layout.setHorizontalGroup(
            pnl10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl4)
                .addContainerGap())
        );
        pnl10Layout.setVerticalGroup(
            pnl10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl4))
        );

        pnl50.setBackground(new java.awt.Color(255, 255, 0));
        pnl50.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl5.setText("50");

        javax.swing.GroupLayout pnl50Layout = new javax.swing.GroupLayout(pnl50);
        pnl50.setLayout(pnl50Layout);
        pnl50Layout.setHorizontalGroup(
            pnl50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl50Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl5)
                .addContainerGap())
        );
        pnl50Layout.setVerticalGroup(
            pnl50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl50Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl5))
        );

        pnl75.setBackground(new java.awt.Color(255, 255, 0));
        pnl75.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl6.setText("75");

        javax.swing.GroupLayout pnl75Layout = new javax.swing.GroupLayout(pnl75);
        pnl75.setLayout(pnl75Layout);
        pnl75Layout.setHorizontalGroup(
            pnl75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl75Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl6)
                .addContainerGap())
        );
        pnl75Layout.setVerticalGroup(
            pnl75Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl75Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl6))
        );

        pnl100.setBackground(new java.awt.Color(255, 255, 0));
        pnl100.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl7.setText("100");

        javax.swing.GroupLayout pnl100Layout = new javax.swing.GroupLayout(pnl100);
        pnl100.setLayout(pnl100Layout);
        pnl100Layout.setHorizontalGroup(
            pnl100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl100Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl7)
                .addContainerGap())
        );
        pnl100Layout.setVerticalGroup(
            pnl100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl100Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl7))
        );

        pnl200.setBackground(new java.awt.Color(255, 255, 0));
        pnl200.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl8.setText("200");

        javax.swing.GroupLayout pnl200Layout = new javax.swing.GroupLayout(pnl200);
        pnl200.setLayout(pnl200Layout);
        pnl200Layout.setHorizontalGroup(
            pnl200Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl200Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl8)
                .addContainerGap())
        );
        pnl200Layout.setVerticalGroup(
            pnl200Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl200Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl8))
        );

        pnl300.setBackground(new java.awt.Color(255, 255, 0));
        pnl300.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl9.setText("300");

        javax.swing.GroupLayout pnl300Layout = new javax.swing.GroupLayout(pnl300);
        pnl300.setLayout(pnl300Layout);
        pnl300Layout.setHorizontalGroup(
            pnl300Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl300Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lbl9)
                .addContainerGap())
        );
        pnl300Layout.setVerticalGroup(
            pnl300Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl300Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl9))
        );

        pnl400.setBackground(new java.awt.Color(255, 255, 0));
        pnl400.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl10.setText("400");

        javax.swing.GroupLayout pnl400Layout = new javax.swing.GroupLayout(pnl400);
        pnl400.setLayout(pnl400Layout);
        pnl400Layout.setHorizontalGroup(
            pnl400Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl400Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl10)
                .addContainerGap())
        );
        pnl400Layout.setVerticalGroup(
            pnl400Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl400Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl10))
        );

        pnl500.setBackground(new java.awt.Color(255, 255, 0));
        pnl500.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl11.setText("500");

        javax.swing.GroupLayout pnl500Layout = new javax.swing.GroupLayout(pnl500);
        pnl500.setLayout(pnl500Layout);
        pnl500Layout.setHorizontalGroup(
            pnl500Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl500Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl11)
                .addContainerGap())
        );
        pnl500Layout.setVerticalGroup(
            pnl500Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl500Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl11))
        );

        pnl750.setBackground(new java.awt.Color(255, 255, 0));
        pnl750.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl12.setText("750");

        javax.swing.GroupLayout pnl750Layout = new javax.swing.GroupLayout(pnl750);
        pnl750.setLayout(pnl750Layout);
        pnl750Layout.setHorizontalGroup(
            pnl750Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl750Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl12)
                .addContainerGap())
        );
        pnl750Layout.setVerticalGroup(
            pnl750Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl750Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl12))
        );

        pnl25.setBackground(new java.awt.Color(255, 255, 0));
        pnl25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl13.setText("25");

        javax.swing.GroupLayout pnl25Layout = new javax.swing.GroupLayout(pnl25);
        pnl25.setLayout(pnl25Layout);
        pnl25Layout.setHorizontalGroup(
            pnl25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl25Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl13)
                .addContainerGap())
        );
        pnl25Layout.setVerticalGroup(
            pnl25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl25Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl13))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl300, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl750, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl500, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl400, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl200, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl100, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl75, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(pnl25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl300, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl400, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl750, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 3, true));

        pnl1k.setBackground(new java.awt.Color(255, 255, 0));
        pnl1k.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl14.setText("1000");

        javax.swing.GroupLayout pnl1kLayout = new javax.swing.GroupLayout(pnl1k);
        pnl1k.setLayout(pnl1kLayout);
        pnl1kLayout.setHorizontalGroup(
            pnl1kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1kLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl1kLayout.setVerticalGroup(
            pnl1kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1kLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl14))
        );

        pnl5k.setBackground(new java.awt.Color(255, 255, 0));
        pnl5k.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl15.setText("5000");

        javax.swing.GroupLayout pnl5kLayout = new javax.swing.GroupLayout(pnl5k);
        pnl5k.setLayout(pnl5kLayout);
        pnl5kLayout.setHorizontalGroup(
            pnl5kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl5kLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl5kLayout.setVerticalGroup(
            pnl5kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl5kLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl15))
        );

        pnl10k.setBackground(new java.awt.Color(255, 255, 0));
        pnl10k.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl16.setText("10000");

        javax.swing.GroupLayout pnl10kLayout = new javax.swing.GroupLayout(pnl10k);
        pnl10k.setLayout(pnl10kLayout);
        pnl10kLayout.setHorizontalGroup(
            pnl10kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl10kLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl10kLayout.setVerticalGroup(
            pnl10kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl10kLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl16))
        );

        pnl25k.setBackground(new java.awt.Color(255, 255, 0));
        pnl25k.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl17.setText("25000");

        javax.swing.GroupLayout pnl25kLayout = new javax.swing.GroupLayout(pnl25k);
        pnl25k.setLayout(pnl25kLayout);
        pnl25kLayout.setHorizontalGroup(
            pnl25kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl25kLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl25kLayout.setVerticalGroup(
            pnl25kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl25kLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl17))
        );

        pnl50k.setBackground(new java.awt.Color(255, 255, 0));
        pnl50k.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl18.setText("50000");

        javax.swing.GroupLayout pnl50kLayout = new javax.swing.GroupLayout(pnl50k);
        pnl50k.setLayout(pnl50kLayout);
        pnl50kLayout.setHorizontalGroup(
            pnl50kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl50kLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl50kLayout.setVerticalGroup(
            pnl50kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl50kLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl18))
        );

        pnl75k.setBackground(new java.awt.Color(255, 255, 0));
        pnl75k.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl19.setText("75000");

        javax.swing.GroupLayout pnl75kLayout = new javax.swing.GroupLayout(pnl75k);
        pnl75k.setLayout(pnl75kLayout);
        pnl75kLayout.setHorizontalGroup(
            pnl75kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl75kLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl75kLayout.setVerticalGroup(
            pnl75kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl75kLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl19))
        );

        pnl100k.setBackground(new java.awt.Color(255, 255, 0));
        pnl100k.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl20.setText("100000");

        javax.swing.GroupLayout pnl100kLayout = new javax.swing.GroupLayout(pnl100k);
        pnl100k.setLayout(pnl100kLayout);
        pnl100kLayout.setHorizontalGroup(
            pnl100kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl100kLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl100kLayout.setVerticalGroup(
            pnl100kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl100kLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl20))
        );

        pnl200k.setBackground(new java.awt.Color(255, 255, 0));
        pnl200k.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl21.setText("200000");

        javax.swing.GroupLayout pnl200kLayout = new javax.swing.GroupLayout(pnl200k);
        pnl200k.setLayout(pnl200kLayout);
        pnl200kLayout.setHorizontalGroup(
            pnl200kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl200kLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl200kLayout.setVerticalGroup(
            pnl200kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl200kLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl21))
        );

        pnl300k.setBackground(new java.awt.Color(255, 255, 0));

        lbl22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl22.setText("300000");

        javax.swing.GroupLayout pnl300kLayout = new javax.swing.GroupLayout(pnl300k);
        pnl300k.setLayout(pnl300kLayout);
        pnl300kLayout.setHorizontalGroup(
            pnl300kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl300kLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl300kLayout.setVerticalGroup(
            pnl300kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl300kLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl22))
        );

        pnl400k.setBackground(new java.awt.Color(255, 255, 0));
        pnl400k.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl23.setText("400000");

        javax.swing.GroupLayout pnl400kLayout = new javax.swing.GroupLayout(pnl400k);
        pnl400k.setLayout(pnl400kLayout);
        pnl400kLayout.setHorizontalGroup(
            pnl400kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl400kLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl400kLayout.setVerticalGroup(
            pnl400kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl400kLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl23))
        );

        pnl500k.setBackground(new java.awt.Color(255, 255, 0));
        pnl500k.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl24.setText("500000");

        javax.swing.GroupLayout pnl500kLayout = new javax.swing.GroupLayout(pnl500k);
        pnl500k.setLayout(pnl500kLayout);
        pnl500kLayout.setHorizontalGroup(
            pnl500kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl500kLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl500kLayout.setVerticalGroup(
            pnl500kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl500kLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl24))
        );

        pnl750k.setBackground(new java.awt.Color(255, 255, 0));
        pnl750k.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl25.setText("750000");

        javax.swing.GroupLayout pnl750kLayout = new javax.swing.GroupLayout(pnl750k);
        pnl750k.setLayout(pnl750kLayout);
        pnl750kLayout.setHorizontalGroup(
            pnl750kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl750kLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl750kLayout.setVerticalGroup(
            pnl750kLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl750kLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl25))
        );

        pnl1m.setBackground(new java.awt.Color(255, 255, 0));
        pnl1m.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl26.setText("1000000");

        javax.swing.GroupLayout pnl1mLayout = new javax.swing.GroupLayout(pnl1m);
        pnl1m.setLayout(pnl1mLayout);
        pnl1mLayout.setHorizontalGroup(
            pnl1mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1mLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl1mLayout.setVerticalGroup(
            pnl1mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1mLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl26))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl1k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl5k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl10k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl25k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl50k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl75k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl100k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl200k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl500k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl750k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl300k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl400k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl1m, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnl1k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl5k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl10k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl25k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl50k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl75k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl100k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl200k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl300k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl400k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl500k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl750k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl1m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        case1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case1.setText("1");
        case1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case1ActionPerformed(evt);
            }
        });

        case2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case2.setText("2");
        case2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case2ActionPerformed(evt);
            }
        });

        case3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case3.setText("3");
        case3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case3ActionPerformed(evt);
            }
        });

        case4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case4.setText("4");
        case4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case4ActionPerformed(evt);
            }
        });

        case5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case5.setText("5");
        case5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case5ActionPerformed(evt);
            }
        });

        case6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case6.setText("6");
        case6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case6ActionPerformed(evt);
            }
        });

        case11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case11.setText("11");
        case11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case11ActionPerformed(evt);
            }
        });

        case14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case14.setText("14");
        case14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case14ActionPerformed(evt);
            }
        });

        case19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case19.setText("19");
        case19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case19ActionPerformed(evt);
            }
        });

        case24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case24.setText("24");
        case24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case24ActionPerformed(evt);
            }
        });

        case12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case12.setText("12");
        case12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case12ActionPerformed(evt);
            }
        });

        case15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case15.setText("15");
        case15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case15ActionPerformed(evt);
            }
        });

        case20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case20.setText("20");
        case20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case20ActionPerformed(evt);
            }
        });

        case7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case7.setText("7");
        case7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case7ActionPerformed(evt);
            }
        });

        case25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case25.setText("25");
        case25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case25ActionPerformed(evt);
            }
        });

        case8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case8.setText("8");
        case8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case8ActionPerformed(evt);
            }
        });

        case13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case13.setText("13");
        case13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case13ActionPerformed(evt);
            }
        });

        case16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case16.setText("16");
        case16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case16ActionPerformed(evt);
            }
        });

        case21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case21.setText("21");
        case21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case21ActionPerformed(evt);
            }
        });

        case26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case26.setText("26");
        case26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case26ActionPerformed(evt);
            }
        });

        case9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case9.setText("9");
        case9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case9ActionPerformed(evt);
            }
        });

        case10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case10.setText("10");
        case10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case10ActionPerformed(evt);
            }
        });

        case17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case17.setText("17");
        case17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case17ActionPerformed(evt);
            }
        });

        case18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case18.setText("18");
        case18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case18ActionPerformed(evt);
            }
        });

        case22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case22.setText("22");
        case22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case22ActionPerformed(evt);
            }
        });

        case23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        case23.setText("23");
        case23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case23ActionPerformed(evt);
            }
        });

        jPanel30.setBackground(new java.awt.Color(0, 0, 0));
        jPanel30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 3, true));

        lblmsm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblmsm.setForeground(new java.awt.Color(255, 255, 255));
        lblmsm.setText("Seleccione un portafolio para empezar");

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblmsm, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblmsm)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Selecciona");

        lblcout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblcout.setText("6");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Tu maletin");

        lblselec.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblselec.setText("?");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("maletines");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(case1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(case6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(case11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(case14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(case19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(case2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(case7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(case15)
                            .addComponent(case20)
                            .addComponent(case24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(case3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(case8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(case12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(case16)
                            .addComponent(case21)
                            .addComponent(case25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(case9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(case4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(case17)
                            .addComponent(case22)
                            .addComponent(case26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(case13)
                            .addComponent(case10)
                            .addComponent(case5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(case18)
                            .addComponent(case23))
                        .addGap(31, 31, 31)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblselec)
                                .addGap(41, 41, 41)))
                        .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lblcout)))))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(case1)
                            .addComponent(case5)
                            .addComponent(case2)
                            .addComponent(case4)
                            .addComponent(case3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(case6)
                            .addComponent(case7)
                            .addComponent(case8)
                            .addComponent(case9)
                            .addComponent(case10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(case11)
                            .addComponent(case12)
                            .addComponent(case13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(case14)
                            .addComponent(case15)
                            .addComponent(case16)
                            .addComponent(case17)
                            .addComponent(case18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(case19)
                            .addComponent(case20)
                            .addComponent(case21)
                            .addComponent(case22)
                            .addComponent(case23))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(case24)
                            .addComponent(case25)
                            .addComponent(case26)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblselec)
                            .addComponent(lblcout))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void case1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case1ActionPerformed
case1.setVisible(case1.isSelected()==false);
if(case1.isSelected()){
    if(seleccionados!=7){Color color = new Color(51,51,0);
pnl750.setBackground(color);
Double perdido = Double.valueOf(lbl12.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case1.getText());
    price= Double.valueOf(lbl12.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case1ActionPerformed

    private void case3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case3ActionPerformed
    case3.setVisible(case3.isSelected()==false);
if(case3.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl5k.setBackground(color);
Double perdido = Double.valueOf(lbl15.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case3.getText());
    price= Double.valueOf(lbl15.getText());
    }
};    // TODO add your handling code here:
    }//GEN-LAST:event_case3ActionPerformed

    private void case4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case4ActionPerformed
      case4.setVisible(case4.isSelected()==false); 
      if(case4.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl200.setBackground(color);
Double perdido = Double.valueOf(lbl8.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case4.getText());
    price= Double.valueOf(lbl8.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case4ActionPerformed

    private void case2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case2ActionPerformed
case2.setVisible(case2.isSelected()==false);
if(case2.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl750k.setBackground(color);
Double perdido = Double.valueOf(lbl25.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case2.getText());
    price= Double.valueOf(lbl25.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case2ActionPerformed

    private void case5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case5ActionPerformed
     case5.setVisible(case5.isSelected()==false);
     if(case5.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl50.setBackground(color);
Double perdido = Double.valueOf(lbl5.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case5.getText());
    price= Double.valueOf(lbl5.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case5ActionPerformed

    private void case6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case6ActionPerformed
      case6.setVisible(case6.isSelected()==false);  
        if(case6.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl500k.setBackground(color);
Double perdido = Double.valueOf(lbl24.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case6.getText());
    price= Double.valueOf(lbl24.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case6ActionPerformed

    private void case7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case7ActionPerformed
       case7.setVisible(case7.isSelected()==false); 
  if(case7.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl1.setBackground(color);
Double perdido = Double.valueOf(lbl1.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case7.getText());
    price= Double.valueOf(lbl1.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case7ActionPerformed

    private void case8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case8ActionPerformed
      case8.setVisible(case8.isSelected()==false);
      if(case8.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl10k.setBackground(color);
Double perdido = Double.valueOf(lbl16.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case8.getText());
    price= Double.valueOf(lbl16.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case8ActionPerformed

    private void case9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case9ActionPerformed
      case9.setVisible(case9.isSelected()==false);
      if(case9.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl200k.setBackground(color);
Double perdido = Double.valueOf(lbl21.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case9.getText());
    price= Double.valueOf(lbl21.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case9ActionPerformed

    private void case10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case10ActionPerformed
     case10.setVisible(case10.isSelected()==false);
     if(case10.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl10.setBackground(color);
Double perdido = Double.valueOf(lbl4.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case10.getText());
    price= Double.valueOf(lbl4.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case10ActionPerformed

    private void case11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case11ActionPerformed
     case11.setVisible(case11.isSelected()==false);
     if(case11.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl2.setBackground(color);
Double perdido = Double.valueOf(lbl2.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case11.getText());
    price= Double.valueOf(lbl2.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case11ActionPerformed

    private void case12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case12ActionPerformed
       case12.setVisible(case12.isSelected()==false);
       if(case12.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl1k.setBackground(color);
Double perdido = Double.valueOf(lbl14.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case12.getText());
    price= Double.valueOf(lbl14.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case12ActionPerformed

    private void case13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case13ActionPerformed
      case13.setVisible(case13.isSelected()==false);
      if(case13.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl25k.setBackground(color);
Double perdido = Double.valueOf(lbl17.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case13.getText());
    price= Double.valueOf(lbl17.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case13ActionPerformed

    private void case14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case14ActionPerformed
       case14.setVisible(case14.isSelected()==false);
       if(case14.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl5.setBackground(color);
Double perdido = Double.valueOf(lbl3.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case14.getText());
    price= Double.valueOf(lbl3.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case14ActionPerformed

    private void case15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case15ActionPerformed
     case15.setVisible(case15.isSelected()==false);
     if(case15.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl50k.setBackground(color);
Double perdido = Double.valueOf(lbl18.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case15.getText());
    price= Double.valueOf(lbl18.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case15ActionPerformed

    private void case16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case16ActionPerformed
        case16.setVisible(case16.isSelected()==false);
        if(case16.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl100k.setBackground(color);
Double perdido = Double.valueOf(lbl20.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case16.getText());
    price= Double.valueOf(lbl20.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case16ActionPerformed

    private void case17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case17ActionPerformed
     case17.setVisible(case17.isSelected()==false);
     if(case17.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl25.setBackground(color);
Double perdido = Double.valueOf(lbl13.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case17.getText());
    price= Double.valueOf(lbl13.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case17ActionPerformed

    private void case18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case18ActionPerformed
     case18.setVisible(case18.isSelected()==false);
     if(case18.isSelected()){
Color color = new Color(51,51,0);
pnl300k.setBackground(color);
Double perdido = Double.valueOf(lbl22.getText()) ;
total=total-perdido;
make_this();
if(seleccionados==7){
    make_this();
    lblselec.setText(case18.getText());
    price= Double.valueOf(lbl22.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case18ActionPerformed

    private void case19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case19ActionPerformed
     case19.setVisible(case19.isSelected()==false);
     if(case19.isSelected()){
Color color = new Color(51,51,0);
pnl400.setBackground(color);
Double perdido = Double.valueOf(lbl10.getText()) ;
total=total-perdido;
make_this();
if(seleccionados==7){
    make_this();
    lblselec.setText(case19.getText());
    price= Double.valueOf(lbl10.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case19ActionPerformed

    private void case20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case20ActionPerformed
      case20.setVisible(case20.isSelected()==false);
      if(case20.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl75.setBackground(color);
Double perdido = Double.valueOf(lbl6.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case20.getText());
    price= Double.valueOf(lbl6.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case20ActionPerformed

    private void case21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case21ActionPerformed
    case21.setVisible(case21.isSelected()==false);
if(case21.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl400k.setBackground(color);
Double perdido = Double.valueOf(lbl23.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case21.getText());
    price= Double.valueOf(lbl23.getText());
    }
};    // TODO add your handling code here:
    }//GEN-LAST:event_case21ActionPerformed

    private void case22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case22ActionPerformed
      case22.setVisible(case22.isSelected()==false);
      if(case22.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl500.setBackground(color);
Double perdido = Double.valueOf(lbl11.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case22.getText());
    price= Double.valueOf(lbl11.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case22ActionPerformed

    private void case23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case23ActionPerformed
     case23.setVisible(case23.isSelected()==false);
     if(case23.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl1m.setBackground(color);
Double perdido = Double.valueOf(lbl26.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case23.getText());
    price= Double.valueOf(lbl26.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case23ActionPerformed

    private void case24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case24ActionPerformed
     case24.setVisible(case24.isSelected()==false);
     if(case24.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl300.setBackground(color);
Double perdido = Double.valueOf(lbl9.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case24.getText());
    price= Double.valueOf(lbl9.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case24ActionPerformed

    private void case25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case25ActionPerformed
       case25.setVisible(case25.isSelected()==false);
       if(case25.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl100.setBackground(color);
Double perdido = Double.valueOf(lbl7.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case25.getText());
    price= Double.valueOf(lbl7.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case25ActionPerformed

    private void case26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case26ActionPerformed
        case26.setVisible(case26.isSelected()==false);
if(case26.isSelected()){
if(seleccionados!=7){Color color = new Color(51,51,0);
pnl75k.setBackground(color);
Double perdido = Double.valueOf(lbl19.getText()) ;
total=total-perdido;
make_this();
}
    if(seleccionados==7){
    make_this();
    lblselec.setText(case26.getText());
    price= Double.valueOf(lbl9.getText());
    }
};// TODO add your handling code here:
    }//GEN-LAST:event_case26ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton case1;
    private javax.swing.JToggleButton case10;
    private javax.swing.JToggleButton case11;
    private javax.swing.JToggleButton case12;
    private javax.swing.JToggleButton case13;
    private javax.swing.JToggleButton case14;
    private javax.swing.JToggleButton case15;
    private javax.swing.JToggleButton case16;
    private javax.swing.JToggleButton case17;
    private javax.swing.JToggleButton case18;
    private javax.swing.JToggleButton case19;
    private javax.swing.JToggleButton case2;
    private javax.swing.JToggleButton case20;
    private javax.swing.JToggleButton case21;
    private javax.swing.JToggleButton case22;
    private javax.swing.JToggleButton case23;
    private javax.swing.JToggleButton case24;
    private javax.swing.JToggleButton case25;
    private javax.swing.JToggleButton case26;
    private javax.swing.JToggleButton case3;
    private javax.swing.JToggleButton case4;
    private javax.swing.JToggleButton case5;
    private javax.swing.JToggleButton case6;
    private javax.swing.JToggleButton case7;
    private javax.swing.JToggleButton case8;
    private javax.swing.JToggleButton case9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lbl25;
    private javax.swing.JLabel lbl26;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblcout;
    private javax.swing.JLabel lblmsm;
    private javax.swing.JLabel lblselec;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl10;
    private javax.swing.JPanel pnl100;
    private javax.swing.JPanel pnl100k;
    private javax.swing.JPanel pnl10k;
    private javax.swing.JPanel pnl1k;
    private javax.swing.JPanel pnl1m;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl200;
    private javax.swing.JPanel pnl200k;
    private javax.swing.JPanel pnl25;
    private javax.swing.JPanel pnl25k;
    private javax.swing.JPanel pnl300;
    private javax.swing.JPanel pnl300k;
    private javax.swing.JPanel pnl400;
    private javax.swing.JPanel pnl400k;
    private javax.swing.JPanel pnl5;
    private javax.swing.JPanel pnl50;
    private javax.swing.JPanel pnl500;
    private javax.swing.JPanel pnl500k;
    private javax.swing.JPanel pnl50k;
    private javax.swing.JPanel pnl5k;
    private javax.swing.JPanel pnl75;
    private javax.swing.JPanel pnl750;
    private javax.swing.JPanel pnl750k;
    private javax.swing.JPanel pnl75k;
    // End of variables declaration//GEN-END:variables
}
